petclinic/urls.py
#!/usr/bin/env python3
from django.urls import path

from . import views

app_name="petclinic"
urlpatterns = [
    # /petclinic/owner
    path('', views.IndexView.as_view(), name='index'),
    # List owners
    path('owner', views.OwnerView.as_view(), name='owners'),

    # /petclinic/owner/5
    path('owner/<int:pk>', views.OwnerDetail.as_view(), name='owner'),

    # /petclinic/owner/create
    path('owner/create', views.OwnerCreate.as_view(), name='ownercreate'),

    # /petclinic/owner/delete
    path('owner/<int:pk>/delete', views.OwnerDelete.as_view(), name='ownerdelete'),
    # url(r'^owner/(?P<pk>\d+)/delete/$', views.OwnerDelete.as_view(), name='ownerdelete'),

    # /petclinic/animal
    path('animal', views.AnimalView.as_view(), name='animals'),

    # /petclinic/animal/7
    path('animal/<int:pk>', views.AnimalDetail.as_view(), name='animal'),

]

petclinic/models.py
from django.db import models
from django.urls import reverse
from enum import Enum

# Create your models here.

class Sex(Enum):
    UNKNOWN = 0
    FEMALE = 1
    MALE = 2

    @classmethod
    def choices(cls):
        return [(key.value, key.name) for key in cls]

class Owner(models.Model):
    name = models.CharField(max_length=50)
    number = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('petclinic:owner', kwargs={'pk': self.pk})

class Animal(models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    sex = models.IntegerField(choices=Sex.choices(), default=Sex.UNKNOWN)

    def __str__(self):
        return self.name

petclinic/views.py
from django.urls import reverse_lazy
from django.views import generic

from .models import Owner, Animal

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'petclinic/index.html'
    context_object_name = 'owner_list'

    def get_queryset(self):
        """Returns all Owner"""
        return Owner.objects.all()

class OwnerView(generic.ListView):
    template_name = 'petclinic/owner_list.html'
    context_object_name = 'owner_list'

    def get_queryset(self):
        "Returns all Owner"
        return Owner.objects.all()


class OwnerDetail(generic.DetailView):
    template_name = 'petclinic/owner_view.html'
    model = Owner


class OwnerCreate(generic.CreateView):
    model = Owner
    fields = ['name', 'number']


class OwnerDelete(generic.DeleteView):
    model = Owner
    success_url = reverse_lazy('petclinic:owners')


class AnimalView(generic.ListView):
    template_name = 'petclinic/animal_list.html'
    context_object_name = 'animal_list'

    def get_queryset(self):
        return Animal.objects.all()


class AnimalDetail(generic.DetailView):
    template_name = 'petclinic/animal_view.html'
    model = Animal

petclinic/templates/petclinic/animal_list.html
{% extends 'petclinic/base.html' %}
{% block content %}
{% if animal_list %}
<h3>Select an animal:</h3>
<ul>
    {% for animal in animal_list %}
    <li><a href="{% url 'petclinic:animal' animal.id %}">{{ animal.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No Animals are available.</p>
{% endif %}
{% endblock %}

petclinic/templates/petclinic/animal_view.html
{% extends 'petclinic/base.html' %}
{% block content %}
<h2>{{ animal.name }}</h2>
<ul>
  <li>Sex: {{animal.sex}}</li>
  <li>Owner: <a href="{% url 'petclinic:owner' animal.owner.id %}">{{animal.owner.name}}</a> </li>
</ul>
{% endblock %}

petclinic/templates/petclinic/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Petclinic</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'petclinic/favicon.ico' %}"/>
  </head>
  <body>
  <link rel="stylesheet" type="text/css" href="{% static 'petclinic/style.css' %}">
  <div class="page-header">
    <h1><a href="{% url 'petclinic:index' %}">Petclinic - For all we care</a></h1>
  </div>
  {% block content %}
  {% endblock %}
  </body>
</html>

petclinic/templates/petclinic/index.html
{% extends 'petclinic/base.html' %}
{% block content %}
<h2>
  <ul>
    <li><a href="{% url 'petclinic:owners' %}">Owner-list</a></li>
    <li><a href="{% url 'petclinic:animals' %}">Animals-list</a></li>
  </ul>
</h2>
{% endblock %}

petclinic/templates/petclinic/owner_confirm_delete.html
{% extends 'petclinic/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="button" type="submit" value="Confirm">
</form>
{% endblock %}

petclinic/templates/petclinic/owner_form.html
{% extends 'petclinic/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="button" type="submit" value="Create">
</form>
{% endblock %}

petclinic/templates/petclinic/owner_list.html
{% extends 'petclinic/base.html' %}
{% block content %}
{% if owner_list %}
<h3>Select a client:</h3>
<ul>
    {% for owner in owner_list %}
    <li><a href="{% url 'petclinic:owner' owner.id %}">{{ owner.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No Customes are available.</p>
{% endif %}
<a href="{% url 'petclinic:ownercreate' %}" class="button">Create Owner</a>
{% endblock %}

petclinic/templates/petclinic/owner_view.html
{% extends 'petclinic/base.html' %}
{% block content %}

{% if owner %}
  <h1>{{ owner.name }}</h1>
  <h2>List of pets:</h2>
  {% for animal in owner.animal_set.all %}
  <li><a href="{% url 'petclinic:animal' animal.id %}">{{animal.name}}</a></li>
  {% endfor %}
  <a href="{% url 'petclinic:ownerdelete' owner.id %}" class="red-button">Delete Owner</a>
{% else %}
  <p>No owner id</p>
{% endif %}
{% endblock %}